import type { Brand, Product, Inspiration, ExhibitionPiece } from "./types";

// Sample data shown until Supabase is connected (or while a table is empty).
// The moment NEXT_PUBLIC_SUPABASE_URL / KEY are set and tables have rows,
// the data layer switches to live data automatically.

export const seedBrands: Brand[] = [
  {
    id: "seed-lee",
    slug: "lee",
    name: "Lee",
    image_url: null,
    target: "20–30s / casual / vintage",
    price_range: "₩50,000 – ₩200,000",
    mood: "Vintage · Americana · Workwear",
    description:
      "미국 데님의 헤리티지를 지닌 브랜드. 빈티지 워싱과 워크웨어 실루엣이 '분장'이 아니라 실제로 입어온 옷처럼 자연스럽게 읽힌다.",
    brand_character: ["Vintage", "Casual", "Americana", "Workwear"],
    signature: "Denim · Logo · Vintage wash",
    core_products: "Denim · Jacket · Cap",
    materials: "Denim, heavy cotton, corduroy",
    color_palette: "Indigo, ecru, faded brown",
    sns_content: "실착 위주의 룩북, 바랜 톤의 필름 감성 이미지",
    what_i_like: "워싱이 억지스럽지 않고 진짜 낡은 것처럼 자연스럽다.",
    what_i_would_change: "실루엣을 조금 더 현대적이고 깔끔하게.",
  },
  {
    id: "seed-carhartt",
    slug: "carhartt-wip",
    name: "Carhartt WIP",
    image_url: null,
    target: "20–30s / workwear / street",
    price_range: "₩100,000 – ₩250,000",
    mood: "Workwear · Utility · Vintage-not-kitsch",
    description:
      "진짜 작업복의 헤리티지를 그대로 라이프스타일 웨어로 번역한 브랜드. 디테일을 과시하지 않고 소재가 스스로 말한다.",
    brand_character: ["Workwear", "Utility", "Street", "Heritage"],
    signature: "Duck canvas · Square C label",
    core_products: "Detroit Jacket · Double Knee Pant",
    materials: "Duck canvas, corduroy, heavy cotton",
    color_palette: "Hamilton brown, olive, black",
    sns_content: "작업복 무드의 룩북, 스케이터·뮤지션 커뮤니티",
    what_i_like: "디테일이 절제돼 있고 소재가 스스로 말한다.",
    what_i_would_change: "핏을 조금 더 컨템포러리하게.",
  },
];

export const seedProducts: Product[] = [
  {
    id: "seed-p-detroit",
    brand_id: "seed-carhartt",
    name: "Detroit Jacket",
    image_urls: null,
    price: "₩239,000",
    category: "Outerwear",
    color: "Hamilton Brown",
    material: "12oz Dearborn Canvas",
    silhouette: "Boxy, cropped",
    detail: "Corduroy collar · Blanket lining",
    what_i_like: "카라의 코듀로이 대비와 각진 실루엣.",
    what_i_would_change: "총장을 살짝 더 길게.",
  },
  {
    id: "seed-p-doubleknee",
    brand_id: "seed-carhartt",
    name: "Double Knee Pant",
    image_urls: null,
    price: "₩159,000",
    category: "Bottom",
    color: "Dusty H Brown",
    material: "Dearborn Canvas",
    silhouette: "Relaxed straight",
    detail: "Double-layer knee · Utility pocket",
    what_i_like: "무릎 이중 패널의 기능적 인상.",
    what_i_would_change: "밑단을 조금 더 테이퍼드하게.",
  },
  {
    id: "seed-p-rider",
    brand_id: "seed-lee",
    name: "101 Rider Jacket",
    image_urls: null,
    price: "₩189,000",
    category: "Outerwear",
    color: "Vintage Indigo",
    material: "Cotton 100%",
    silhouette: "Cropped, structured",
    detail: "Vintage wash · Chest pleats",
    what_i_like: "짧은 기장과 각진 어깨의 밸런스.",
    what_i_would_change: "버튼 마감을 더 절제되게.",
  },
];

export const seedInspiration: Inspiration[] = [
  {
    id: "seed-i1",
    title: "Empty background, full silhouette",
    image_url: null,
    category: "Styling",
    source: "Pinterest",
    note: "모델보다 옷의 실루엣이 강조돼서 좋음. 배경이 완전히 비워져 있다.",
    tags: ["silhouette", "minimal"],
  },
  {
    id: "seed-i2",
    title: "Faded, not costume",
    image_url: null,
    category: "Color",
    source: "Instagram",
    note: "빈티지한데 촌스럽지 않음. 컬러가 바랜 듯 눌려있는 톤.",
    tags: ["vintage", "color"],
  },
  {
    id: "seed-i3",
    title: "Laid-flat still life",
    image_url: null,
    category: "Photography",
    source: "Lookbook",
    note: "제품을 바닥에 눕혀서 찍은 방식이 좋음. 착용컷보다 물성이 잘 보인다.",
    tags: ["still-life", "product"],
  },
  {
    id: "seed-i4",
    title: "Grey wall, daylight",
    image_url: null,
    category: "Photography",
    source: "Pinterest",
    note: "군더더기 없는 회색 배경 + 자연광. 고급스러운데 힘을 뺀 느낌.",
    tags: ["minimal", "lighting"],
  },
  {
    id: "seed-i5",
    title: "Utility pocket study",
    image_url: null,
    category: "Detail",
    source: "Archive",
    note: "포켓 배치가 옆선 뒤로 밀려 있어 실루엣이 깔끔하게 유지된다.",
    tags: ["detail", "workwear"],
  },
];

export const seedExhibition: ExhibitionPiece[] = [
  {
    id: "seed-e1",
    title: "Field Jacket 01",
    image_urls: null,
    category: "Outerwear",
    concept:
      "기존 밀리터리 자켓의 구조를 유지하면서 여성의 체형에 맞게 실루엣을 수정.",
    design_notes: "어깨는 드롭, 카라 각도를 낮추고 포켓 위치를 재배치.",
    material: "Cotton twill 100%",
    silhouette: "Cropped, waist-adjusted",
    details: "Cropped length · Oversized pocket · Waist adjustment",
    date: "2026 SS",
  },
  {
    id: "seed-e2",
    title: "Work Jacket 02",
    image_urls: null,
    category: "Outerwear",
    concept: "워크 자켓의 기능적 디테일을 최소한으로 덜어낸 도식.",
    design_notes: "포켓 4개를 2개로 축소, 밑단 조임 제거.",
    material: "Duck canvas",
    silhouette: "Boxy",
    details: "Two-pocket · Dropped shoulder",
    date: "2026 SS",
  },
  {
    id: "seed-e3",
    title: "Cargo Pant 01",
    image_urls: null,
    category: "Bottom",
    concept: "카고 포켓을 옆선 뒤로 밀어 실루엣을 깔끔하게.",
    design_notes: "포켓 위치 재배치, 밑단 살짝 테이퍼드.",
    material: "Ripstop cotton",
    silhouette: "Tapered",
    details: "Rear-set cargo pocket · Tapered hem",
    date: "2026 SS",
  },
];
